<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MillenovaDeployConsole.Core\MillenovaDeployConsole.Core.csproj" />
    <ProjectReference Include="..\MillenovaDeployConsole.Infrastructure\MillenovaDeployConsole.Infrastructure.csproj" />
    <ProjectReference Include="..\MillenovaDeployConsole.WslBridge\MillenovaDeployConsole.WslBridge.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
